//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPetshop_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_pessoas_empresa_pet
    {
        public string NOME_PET { get; set; }
        public string ESPECIE_PET { get; set; }
        public int ID_PET { get; set; }
        public string IDADE { get; set; }
        public string RACA_PET { get; set; }
        public string SEXO_PET { get; set; }
        public string NOME_PROPRIETARIO { get; set; }
        public string CELULAR { get; set; }
        public string FIXO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public bool ATIVO { get; set; }
        public string FANTASIA { get; set; }
        public string RAZAO_SOCIAL { get; set; }
    }
}
