//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPetshop_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFOP
    {
        public int ID_CFOP { get; set; }
        public string CFOP1 { get; set; }
        public string Descricao { get; set; }
        public string MOV_ESTQ { get; set; }
        public string ATUALIZA_CUSTO { get; set; }
        public string TIPO_MOV { get; set; }
        public string ATIVO { get; set; }
    }
}
