//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPetshop_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compromissos
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string Descricao { get; set; }
        public int USUARIO_CRIOU_COMP { get; set; }
        public Nullable<int> USUARIO_P_COMP { get; set; }
        public string Entidade_Registro { get; set; }
        public Nullable<int> ID_REGISTRO { get; set; }
        public Nullable<bool> Concluido { get; set; }
    }
}
