
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 10/21/2021 13:53:04
-- Generated from EDMX file: C:\Users\Administrator\Documents\repos\SistemaPetshop 2.0\SistemaPetshop 2.0\MODELPET.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [LOJA_PET];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_ATENDIMENTO_VETINTERNACAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[INTERNACAO] DROP CONSTRAINT [FK_ATENDIMENTO_VETINTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[FK_ATENDIMENTO_VETRECEITA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RECEITA] DROP CONSTRAINT [FK_ATENDIMENTO_VETRECEITA];
GO
IF OBJECT_ID(N'[dbo].[FK_ATENDIMENTO_VETSERVICO_VETERINARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SERVICO_VETERINARIO] DROP CONSTRAINT [FK_ATENDIMENTO_VETSERVICO_VETERINARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_ATENDIMENTO_VETTOTAL_ATENDIMENTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TOTAL_ATENDIMENTO] DROP CONSTRAINT [FK_ATENDIMENTO_VETTOTAL_ATENDIMENTO];
GO
IF OBJECT_ID(N'[dbo].[FK_CIRURGIAATENDIMENTO_VET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ATENDIMENTO_VET] DROP CONSTRAINT [FK_CIRURGIAATENDIMENTO_VET];
GO
IF OBJECT_ID(N'[dbo].[FK_CIRURGIAINTERNACAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[INTERNACAO] DROP CONSTRAINT [FK_CIRURGIAINTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TOTAL_INTERNACAO_CIRURGIA] DROP CONSTRAINT [FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA1]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TOTAL_INTERNACAO_CIRURGIA] DROP CONSTRAINT [FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA1];
GO
IF OBJECT_ID(N'[dbo].[FK_CIRURGIAVET_CIRURGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[VET_CIRURGIA] DROP CONSTRAINT [FK_CIRURGIAVET_CIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_ClienteATENDIMENTO_VET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ATENDIMENTO_VET] DROP CONSTRAINT [FK_ClienteATENDIMENTO_VET];
GO
IF OBJECT_ID(N'[dbo].[FK_ClienteCIRURGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CIRURGIA] DROP CONSTRAINT [FK_ClienteCIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_ClienteINTERNACAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[INTERNACAO] DROP CONSTRAINT [FK_ClienteINTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[FK_EMAILEMPRESA_EMAIL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[EMPRESA_EMAIL] DROP CONSTRAINT [FK_EMAILEMPRESA_EMAIL];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESA_EMAIL1]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[EMPRESA_EMAIL] DROP CONSTRAINT [FK_EMPRESA_EMAIL1];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESAATENDIMENTO_VET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ATENDIMENTO_VET] DROP CONSTRAINT [FK_EMPRESAATENDIMENTO_VET];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESACIRURGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CIRURGIA] DROP CONSTRAINT [FK_EMPRESACIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESACONFIG]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[EMPRESA] DROP CONSTRAINT [FK_EMPRESACONFIG];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESAEMPRESA_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[EMPRESA_USUARIO] DROP CONSTRAINT [FK_EMPRESAEMPRESA_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESAEMPRESA_VETERINARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[EMPRESA_VETERINARIO] DROP CONSTRAINT [FK_EMPRESAEMPRESA_VETERINARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESAINTERNACAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[INTERNACAO] DROP CONSTRAINT [FK_EMPRESAINTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[FK_INTERNACAORECEITA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RECEITA] DROP CONSTRAINT [FK_INTERNACAORECEITA];
GO
IF OBJECT_ID(N'[dbo].[FK_INTERNACAOSERVICO_VETERINARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SERVICO_VETERINARIO] DROP CONSTRAINT [FK_INTERNACAOSERVICO_VETERINARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_INTERNACAOTOTAL_INTERNACAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TOTAL_INTERNACAO_CIRURGIA] DROP CONSTRAINT [FK_INTERNACAOTOTAL_INTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[FK_PAGAMENTOSPAGAMENTOS_ATENDIMENTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PAGAMENTOS_ATENDIMENTOS] DROP CONSTRAINT [FK_PAGAMENTOSPAGAMENTOS_ATENDIMENTO];
GO
IF OBJECT_ID(N'[dbo].[FK_PAGAMENTOSPAGAMENTOS_INTERNACAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PAGAMENTOS_INTERNACAO] DROP CONSTRAINT [FK_PAGAMENTOSPAGAMENTOS_INTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[FK_PERFILUSUARIOS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USUARIOS] DROP CONSTRAINT [FK_PERFILUSUARIOS];
GO
IF OBJECT_ID(N'[dbo].[FK_PETATENDIMENTO_VET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ATENDIMENTO_VET] DROP CONSTRAINT [FK_PETATENDIMENTO_VET];
GO
IF OBJECT_ID(N'[dbo].[FK_PETCIRURGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CIRURGIA] DROP CONSTRAINT [FK_PETCIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_PETCliente]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PETS] DROP CONSTRAINT [FK_PETCliente];
GO
IF OBJECT_ID(N'[dbo].[FK_PETINTERNACAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[INTERNACAO] DROP CONSTRAINT [FK_PETINTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[FK_RECEITACIRURGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RECEITA] DROP CONSTRAINT [FK_RECEITACIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_SERVICOSERVICO_VETERINARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SERVICO_VETERINARIO] DROP CONSTRAINT [FK_SERVICOSERVICO_VETERINARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_TAXASPAGAMENTOS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PAGAMENTOS] DROP CONSTRAINT [FK_TAXASPAGAMENTOS];
GO
IF OBJECT_ID(N'[dbo].[FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PAGAMENTOS_ATENDIMENTOS] DROP CONSTRAINT [FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO];
GO
IF OBJECT_ID(N'[dbo].[FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO1]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PAGAMENTOS_INTERNACAO] DROP CONSTRAINT [FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO1];
GO
IF OBJECT_ID(N'[dbo].[FK_USUARIOSEMPRESA_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[EMPRESA_USUARIO] DROP CONSTRAINT [FK_USUARIOSEMPRESA_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_VeterinariosATENDIMENTO_VET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ATENDIMENTO_VET] DROP CONSTRAINT [FK_VeterinariosATENDIMENTO_VET];
GO
IF OBJECT_ID(N'[dbo].[FK_VeterinariosCIRURGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CIRURGIA] DROP CONSTRAINT [FK_VeterinariosCIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_VeterinariosEMPRESA_VETERINARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[EMPRESA_VETERINARIO] DROP CONSTRAINT [FK_VeterinariosEMPRESA_VETERINARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_VeterinariosINTERNACAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[INTERNACAO] DROP CONSTRAINT [FK_VeterinariosINTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[FK_VeterinariosSERVICO_VETERINARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SERVICO_VETERINARIO] DROP CONSTRAINT [FK_VeterinariosSERVICO_VETERINARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_VeterinariosVET_CIRURGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[VET_CIRURGIA] DROP CONSTRAINT [FK_VeterinariosVET_CIRURGIA];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[ATENDIMENTO_VET]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ATENDIMENTO_VET];
GO
IF OBJECT_ID(N'[dbo].[CEP]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CEP];
GO
IF OBJECT_ID(N'[dbo].[CFOP]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CFOP];
GO
IF OBJECT_ID(N'[dbo].[CIRURGIA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[CLIENTES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CLIENTES];
GO
IF OBJECT_ID(N'[dbo].[Compromissos]', 'U') IS NOT NULL
    DROP TABLE [dbo].[Compromissos];
GO
IF OBJECT_ID(N'[dbo].[CONFIG]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CONFIG];
GO
IF OBJECT_ID(N'[dbo].[EMAIL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[EMAIL];
GO
IF OBJECT_ID(N'[dbo].[EMPRESA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[EMPRESA_EMAIL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[EMPRESA_EMAIL];
GO
IF OBJECT_ID(N'[dbo].[EMPRESA_USUARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[EMPRESA_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[EMPRESA_VETERINARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[EMPRESA_VETERINARIO];
GO
IF OBJECT_ID(N'[dbo].[GRP]', 'U') IS NOT NULL
    DROP TABLE [dbo].[GRP];
GO
IF OBJECT_ID(N'[dbo].[INTERNACAO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[INTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[PAGAMENTOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PAGAMENTOS];
GO
IF OBJECT_ID(N'[dbo].[PAGAMENTOS_ATENDIMENTOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PAGAMENTOS_ATENDIMENTOS];
GO
IF OBJECT_ID(N'[dbo].[PAGAMENTOS_INTERNACAO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PAGAMENTOS_INTERNACAO];
GO
IF OBJECT_ID(N'[dbo].[PERFIL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PERFIL];
GO
IF OBJECT_ID(N'[dbo].[PETS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PETS];
GO
IF OBJECT_ID(N'[dbo].[PROPRIETARIOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROPRIETARIOS];
GO
IF OBJECT_ID(N'[dbo].[RECEITA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[RECEITA];
GO
IF OBJECT_ID(N'[dbo].[SERVICO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SERVICO];
GO
IF OBJECT_ID(N'[dbo].[SERVICO_VETERINARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SERVICO_VETERINARIO];
GO
IF OBJECT_ID(N'[dbo].[TAXAS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TAXAS];
GO
IF OBJECT_ID(N'[dbo].[TOTAL_ATENDIMENTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TOTAL_ATENDIMENTO];
GO
IF OBJECT_ID(N'[dbo].[TOTAL_INTERNACAO_CIRURGIA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TOTAL_INTERNACAO_CIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[Tributacao]', 'U') IS NOT NULL
    DROP TABLE [dbo].[Tributacao];
GO
IF OBJECT_ID(N'[dbo].[USUARIOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USUARIOS];
GO
IF OBJECT_ID(N'[dbo].[VET_CIRURGIA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[VET_CIRURGIA];
GO
IF OBJECT_ID(N'[dbo].[Veterinarios]', 'U') IS NOT NULL
    DROP TABLE [dbo].[Veterinarios];
GO
IF OBJECT_ID(N'[LOJA_PETModelStoreContainer].[b_pessoas_empresa_pet]', 'U') IS NOT NULL
    DROP TABLE [LOJA_PETModelStoreContainer].[b_pessoas_empresa_pet];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'ATENDIMENTO_VET'
CREATE TABLE [dbo].[ATENDIMENTO_VET] (
    [ID_ATENDIMENTO] int IDENTITY(1,1) NOT NULL,
    [ID_VET] int  NOT NULL,
    [ID_PET] int  NOT NULL,
    [ID_EMPRESA] int  NOT NULL,
    [ID_CLIENTE] int  NOT NULL,
    [SINTOMAS] nvarchar(max)  NULL,
    [REQUISICAO_EXAMES] nvarchar(max)  NULL,
    [PESO_PET] float  NOT NULL,
    [ID_INTERNACAO] int  NULL,
    [ID_CIRURGIA] int  NULL,
    [TIPO_ATENDIMENTO] int  NOT NULL,
    [TAXASID_TAXAS] int  NOT NULL
);
GO

-- Creating table 'CEP'
CREATE TABLE [dbo].[CEP] (
    [ID_CEP] int IDENTITY(1,1) NOT NULL,
    [NUM_CEP] varchar(10)  NOT NULL,
    [ENDERECO] nvarchar(40)  NULL,
    [COMPLEMENTO] nvarchar(40)  NULL,
    [BAIRRO] varchar(40)  NOT NULL,
    [CIDADE] varchar(40)  NOT NULL,
    [ESTADO] varchar(20)  NOT NULL,
    [PAIS] nvarchar(40)  NULL,
    [IBGE] nvarchar(25)  NULL,
    [COD_CEP] int  NOT NULL
);
GO

-- Creating table 'CFOP'
CREATE TABLE [dbo].[CFOP] (
    [ID_CFOP] int IDENTITY(1,1) NOT NULL,
    [CFOP1] varchar(5)  NOT NULL,
    [Descricao] varchar(50)  NOT NULL,
    [MOV_ESTQ] char(1)  NOT NULL,
    [ATUALIZA_CUSTO] char(1)  NOT NULL,
    [TIPO_MOV] char(1)  NOT NULL,
    [ATIVO] char(1)  NOT NULL
);
GO

-- Creating table 'CIRURGIA'
CREATE TABLE [dbo].[CIRURGIA] (
    [ID_CIRURGIA] int IDENTITY(1,1) NOT NULL,
    [ID_VET_PRINCIPAL] int  NOT NULL,
    [ID_PET] int  NOT NULL,
    [ID_EMPRESA] int  NOT NULL,
    [ID_CLIENTE] int  NOT NULL,
    [PESO_PET] float  NOT NULL
);
GO

-- Creating table 'CLIENTES'
CREATE TABLE [dbo].[CLIENTES] (
    [COD_CLIENTE] int IDENTITY(1,1) NOT NULL,
    [CPF] varchar(14)  NULL,
    [NOME] varchar(40)  NOT NULL,
    [TELEFONE] varchar(11)  NULL,
    [CELULAR] varchar(11)  NULL,
    [EMAIL] varchar(40)  NULL,
    [CEP] varchar(20)  NULL,
    [RUA] varchar(40)  NULL,
    [NUMERO] varchar(10)  NULL,
    [BAIRRO] varchar(40)  NULL,
    [CIDADE] varchar(40)  NULL,
    [ESTADO] varchar(10)  NULL,
    [ATIVO] char(1)  NULL
);
GO

-- Creating table 'Compromissos'
CREATE TABLE [dbo].[Compromissos] (
    [Id] int IDENTITY(1,1) NOT NULL,
    [Data] datetime  NULL,
    [Hora] time  NULL,
    [Descricao] varchar(max)  NULL,
    [USUARIO_CRIOU_COMP] int  NOT NULL,
    [USUARIO_P_COMP] int  NULL,
    [Entidade_Registro] nvarchar(max)  NULL,
    [ID_REGISTRO] int  NULL,
    [Concluido] bit  NULL
);
GO

-- Creating table 'CONFIG'
CREATE TABLE [dbo].[CONFIG] (
    [ID_CONFIG] int IDENTITY(1,1) NOT NULL,
    [AT_CHV] smallint  NOT NULL,
    [DT_INST] datetime  NOT NULL,
    [DT_VAL] datetime  NOT NULL,
    [MOV_ESTOQUE] bit  NOT NULL,
    [UT_BANHOETOSA] bit  NOT NULL,
    [UT_FIN] bit  NOT NULL,
    [UT_VENDA] bit  NOT NULL,
    [AT_ESTQ] bit  NOT NULL,
    [Val_CPF_CNPJ] bit  NOT NULL,
    [ATIVO] bit  NOT NULL
);
GO

-- Creating table 'EMAIL'
CREATE TABLE [dbo].[EMAIL] (
    [ID_EMAIL] int IDENTITY(1,1) NOT NULL,
    [END_EMAIL] nvarchar(max)  NOT NULL,
    [SENHA] nvarchar(max)  NOT NULL,
    [SMTP] nvarchar(max)  NOT NULL,
    [PORTA] nvarchar(max)  NOT NULL,
    [Req_AUT] bit  NOT NULL,
    [Req_SSL] bit  NOT NULL
);
GO

-- Creating table 'EMPRESA'
CREATE TABLE [dbo].[EMPRESA] (
    [ID_EMPRESA] int IDENTITY(1,1) NOT NULL,
    [RAZAO_SOCIAL] nvarchar(max)  NOT NULL,
    [FANTASIA] nvarchar(max)  NULL,
    [CNPJ_CPF] nvarchar(max)  NULL,
    [IE_RG] nvarchar(max)  NULL,
    [CEP] nvarchar(10)  NULL,
    [ENDERECO] nvarchar(40)  NULL,
    [NUMERO] nvarchar(10)  NULL,
    [COMPLEMENTO] nvarchar(40)  NULL,
    [BAIRRO] nvarchar(40)  NULL,
    [CIDADE] nvarchar(40)  NULL,
    [ESTADO] nvarchar(40)  NULL,
    [PAIS] nvarchar(40)  NULL,
    [TELEFONE] nvarchar(max)  NULL,
    [CELULAR] nvarchar(max)  NULL,
    [EMAIL] nvarchar(max)  NULL,
    [CHV] nvarchar(max)  NULL,
    [ID_CONFIG] int  NOT NULL,
    [IMAGEM] varbinary(max)  NULL,
    [TIPO_EMPRESA] int  NOT NULL,
    [Tipo_juros] nvarchar(1)  NULL,
    [Cobr_juros] nvarchar(1)  NULL,
    [P_juros] decimal(18,0)  NULL,
    [P_MULTA] decimal(18,0)  NULL,
    [ATIVO] bit  NOT NULL
);
GO

-- Creating table 'EMPRESA_EMAIL'
CREATE TABLE [dbo].[EMPRESA_EMAIL] (
    [ID_ASSOCIACAO] int IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] int  NOT NULL,
    [ID_EMAIL] int  NOT NULL
);
GO

-- Creating table 'EMPRESA_USUARIO'
CREATE TABLE [dbo].[EMPRESA_USUARIO] (
    [ID_EMPRESA] int  NOT NULL,
    [ID_USUARIO] int  NOT NULL,
    [ID_ASSOCIACAO] int  NOT NULL
);
GO

-- Creating table 'EMPRESA_VETERINARIO'
CREATE TABLE [dbo].[EMPRESA_VETERINARIO] (
    [ID_ASSOCIACAO] int IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] int  NOT NULL,
    [ID_VET] int  NOT NULL
);
GO

-- Creating table 'GRP'
CREATE TABLE [dbo].[GRP] (
    [COD_GRP] int IDENTITY(1,1) NOT NULL,
    [nome_grupo] varchar(50)  NOT NULL,
    [Prod_Vend] char(1)  NOT NULL
);
GO

-- Creating table 'INTERNACAO'
CREATE TABLE [dbo].[INTERNACAO] (
    [ID_INTERNACAO] int IDENTITY(1,1) NOT NULL,
    [ID_VET] int  NOT NULL,
    [ID_PET] int  NOT NULL,
    [ID_EMPRESA] int  NOT NULL,
    [ID_CLIENTE] int  NOT NULL,
    [PESO_PET] float  NOT NULL,
    [ID_ATENDIMENTO] int  NULL,
    [ID_CIRURGIA] int  NULL
);
GO

-- Creating table 'PAGAMENTOS'
CREATE TABLE [dbo].[PAGAMENTOS] (
    [ID_PAGAMENTOS] int IDENTITY(1,1) NOT NULL,
    [NOME] nvarchar(20)  NOT NULL,
    [TIPO_PAG] int  NULL,
    [ID_TAXAS] int  NOT NULL,
    [Gera_Fin] bit  NOT NULL,
    [ATIVO] bit  NOT NULL
);
GO

-- Creating table 'PAGAMENTOS_ATENDIMENTOS'
CREATE TABLE [dbo].[PAGAMENTOS_ATENDIMENTOS] (
    [ID_ASSOCIACAO] int IDENTITY(1,1) NOT NULL,
    [ID_PAGAMENTO] int  NOT NULL,
    [NOME_PAGAMENTO] nvarchar(max)  NOT NULL,
    [VALOR_PAGAMENTO] decimal(18,0)  NOT NULL,
    [ID_TIPO_ATENDIMENTO] int  NOT NULL,
    [DIVIDO_VEZES] int  NULL,
    [DATA_FECHAMENTO] datetime  NOT NULL
);
GO

-- Creating table 'PAGAMENTOS_INTERNACAO'
CREATE TABLE [dbo].[PAGAMENTOS_INTERNACAO] (
    [ID_ASSOCIACAO] int IDENTITY(1,1) NOT NULL,
    [ID_PAGAMENTO] int  NOT NULL,
    [NOME_PAGAMENTO] nvarchar(max)  NOT NULL,
    [VALOR_PAGAMENTO] decimal(18,2)  NOT NULL,
    [ID_TIPO_ATENDIMENTO] int  NOT NULL,
    [DIVIDO_VEZES] int  NULL,
    [DATA_FECHAMENTO] datetime  NOT NULL
);
GO

-- Creating table 'PERFIL'
CREATE TABLE [dbo].[PERFIL] (
    [ID_PERFIL] int IDENTITY(1,1) NOT NULL,
    [DESCRICAO] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'PETS'
CREATE TABLE [dbo].[PETS] (
    [ID_PET] int IDENTITY(1,1) NOT NULL,
    [NOME_PET] nvarchar(40)  NOT NULL,
    [COD_CLIENTE] int  NOT NULL,
    [RACA_PET] nvarchar(20)  NOT NULL,
    [SEXO_PET] nvarchar(20)  NOT NULL,
    [DATANASC_PET] datetime  NULL,
    [IDADE] nvarchar(20)  NULL,
    [ESPECIE_PET] nvarchar(40)  NULL,
    [ATIVO] bit  NOT NULL
);
GO

-- Creating table 'PROPRIETARIOS'
CREATE TABLE [dbo].[PROPRIETARIOS] (
    [ID_PROPRIETARIO] int IDENTITY(1,1) NOT NULL,
    [NOME_PROPRIETARIO] nvarchar(40)  NOT NULL,
    [EMAIL] nvarchar(30)  NULL,
    [CELULAR] nvarchar(13)  NULL,
    [FIXO] nvarchar(11)  NULL,
    [CEP] nvarchar(8)  NULL,
    [RUA_AVENIDA] nvarchar(40)  NULL,
    [NUMERO] nvarchar(10)  NULL,
    [BAIRRO] nvarchar(40)  NULL,
    [CIDADE] nvarchar(40)  NULL,
    [ESTADO] nvarchar(40)  NULL,
    [ATIVO] bit  NOT NULL
);
GO

-- Creating table 'RECEITA'
CREATE TABLE [dbo].[RECEITA] (
    [ID_RECEITA] int IDENTITY(1,1) NOT NULL,
    [ID_ATENDIMENTO] int  NULL,
    [ID_INTERNACAO] int  NULL,
    [ID_CIRURGIA] int  NULL,
    [DESCRICAO_RECEITA] nvarchar(max)  NOT NULL,
    [DADOS_RECEITA] nvarchar(max)  NOT NULL,
    [DATA_RECEITA] datetime  NOT NULL,
    [ATIVA] bit  NOT NULL
);
GO

-- Creating table 'SERVICO'
CREATE TABLE [dbo].[SERVICO] (
    [ID_SERVICO] int IDENTITY(1,1) NOT NULL,
    [NOME_SERVICO] nvarchar(max)  NOT NULL,
    [VALOR_SERVICO] decimal(18,2)  NOT NULL,
    [ATIVO] bit  NOT NULL
);
GO

-- Creating table 'SERVICO_VETERINARIO'
CREATE TABLE [dbo].[SERVICO_VETERINARIO] (
    [ID_ASSOCIACAO] int IDENTITY(1,1) NOT NULL,
    [ID_SERVICO] int  NOT NULL,
    [NOME_SERVICO] nvarchar(max)  NOT NULL,
    [VALOR_SERVICO] decimal(18,2)  NOT NULL,
    [ID_ATENDIMENTO] int  NULL,
    [ID_INTERNACAO] int  NULL,
    [ID_VET] int  NOT NULL,
    [DATA_EXECUCAO] datetime  NOT NULL
);
GO

-- Creating table 'TOTAL_ATENDIMENTO'
CREATE TABLE [dbo].[TOTAL_ATENDIMENTO] (
    [ID_ASSOCIACAO] int IDENTITY(1,1) NOT NULL,
    [ID_ATENDIMENTO] int  NOT NULL,
    [SUBTOTAL] decimal(18,2)  NOT NULL,
    [DESCONTO] decimal(18,2)  NOT NULL,
    [ACRESCIMO] decimal(18,2)  NOT NULL,
    [TOTAL] decimal(18,2)  NOT NULL,
    [DATA_FINALIZACAO] datetime  NOT NULL
);
GO

-- Creating table 'TOTAL_INTERNACAO_CIRURGIA'
CREATE TABLE [dbo].[TOTAL_INTERNACAO_CIRURGIA] (
    [ID_ASSOCIACAO] int IDENTITY(1,1) NOT NULL,
    [ID_INTERNACAO] int  NULL,
    [ID_CIRURGIA] int  NULL,
    [SUBTOTAL] decimal(18,2)  NOT NULL,
    [DESCONTO] decimal(18,2)  NOT NULL,
    [ACRESCIMO] decimal(18,2)  NOT NULL,
    [TOTAL] decimal(18,2)  NOT NULL,
    [DATA_FINALIZACAO] datetime  NOT NULL
);
GO

-- Creating table 'Tributacao'
CREATE TABLE [dbo].[Tributacao] (
    [ID_TRIB] int IDENTITY(1,1) NOT NULL,
    [TRBID] varchar(3)  NOT NULL,
    [NOME] varchar(50)  NOT NULL,
    [CST_ENTRADA] varchar(3)  NOT NULL,
    [CSOSN_ENTRADA] varchar(4)  NOT NULL,
    [CFOP_ENTRADA_DE] varchar(5)  NOT NULL,
    [CFOP_ENTRADA_DEV_DE] varchar(5)  NOT NULL,
    [CFOP_ENTRADA_DEV_FE] varchar(5)  NOT NULL,
    [CFOP_ENTRADA_FE] varchar(5)  NOT NULL,
    [CST_SAIDA] varchar(3)  NOT NULL,
    [CSOSN_SAIDA] varchar(4)  NOT NULL,
    [CFOP_SAIDA_DE] varchar(5)  NOT NULL,
    [CFOP_SAIDA_FE] varchar(5)  NOT NULL,
    [CFOP_SAIDA_DEV_DE] varchar(5)  NOT NULL,
    [CFOP_SAIDA_DEV_FE] varchar(5)  NOT NULL,
    [ATIVO] char(1)  NOT NULL
);
GO

-- Creating table 'USUARIOS'
CREATE TABLE [dbo].[USUARIOS] (
    [Id_USUARIO] int IDENTITY(1,1) NOT NULL,
    [NOME] nvarchar(max)  NOT NULL,
    [lOGIN] nvarchar(max)  NOT NULL,
    [SENHA] nvarchar(max)  NOT NULL,
    [CONTRA_SENHA] nvarchar(max)  NOT NULL,
    [Email] nvarchar(max)  NOT NULL,
    [ID_PERFIL] int  NOT NULL,
    [ATIVO] bit  NOT NULL
);
GO

-- Creating table 'VET_CIRURGIA'
CREATE TABLE [dbo].[VET_CIRURGIA] (
    [ID_ASSOCIACAO] int IDENTITY(1,1) NOT NULL,
    [ID_VET] int  NOT NULL,
    [ID_CIRURGIA] int  NOT NULL,
    [DIVIDIR_CIRURGIA] bit  NOT NULL
);
GO

-- Creating table 'Veterinarios'
CREATE TABLE [dbo].[Veterinarios] (
    [ID_VET] int IDENTITY(1,1) NOT NULL,
    [NOME_VET] nvarchar(40)  NOT NULL,
    [CPF] nvarchar(11)  NULL,
    [CRMV] nvarchar(20)  NOT NULL,
    [TELEFONE] nvarchar(11)  NULL,
    [CELULAR] nvarchar(13)  NULL,
    [ATIVO] bit  NOT NULL
);
GO

-- Creating table 'TAXAS'
CREATE TABLE [dbo].[TAXAS] (
    [ID_TAXAS] int IDENTITY(1,1) NOT NULL,
    [DESCRICAOTX] nvarchar(max)  NOT NULL,
    [TAXACREDITO1] decimal(18,2)  NOT NULL,
    [TAXACREDITO2] decimal(18,2)  NOT NULL,
    [TAXACREDITO3] decimal(18,2)  NOT NULL,
    [TAXACREDITO4] decimal(18,2)  NOT NULL,
    [TAXACREDITO5] decimal(18,2)  NOT NULL,
    [TAXACREDITO6] decimal(18,2)  NOT NULL,
    [TAXACREDITO7] decimal(18,2)  NOT NULL,
    [TAXACREDITO10] decimal(18,2)  NOT NULL,
    [TAXADEBITO] decimal(18,2)  NOT NULL,
    [TAXABOLETO] decimal(18,2)  NOT NULL,
    [P_DIV] bit  NOT NULL,
    [ATIVO] bit  NOT NULL
);
GO

-- Creating table 'b_pessoas_empresa_pet'
CREATE TABLE [dbo].[b_pessoas_empresa_pet] (
    [NOME_PET] nvarchar(40)  NOT NULL,
    [ESPECIE_PET] nvarchar(40)  NULL,
    [ID_PET] int  NOT NULL,
    [IDADE] nvarchar(20)  NULL,
    [RACA_PET] nvarchar(20)  NOT NULL,
    [SEXO_PET] nvarchar(20)  NOT NULL,
    [NOME_PROPRIETARIO] nvarchar(40)  NOT NULL,
    [CELULAR] nvarchar(13)  NULL,
    [FIXO] nvarchar(11)  NULL,
    [CIDADE] nvarchar(40)  NULL,
    [ESTADO] nvarchar(40)  NULL,
    [ATIVO] bit  NOT NULL,
    [FANTASIA] nvarchar(max)  NULL,
    [RAZAO_SOCIAL] nvarchar(max)  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ID_ATENDIMENTO] in table 'ATENDIMENTO_VET'
ALTER TABLE [dbo].[ATENDIMENTO_VET]
ADD CONSTRAINT [PK_ATENDIMENTO_VET]
    PRIMARY KEY CLUSTERED ([ID_ATENDIMENTO] ASC);
GO

-- Creating primary key on [ID_CEP] in table 'CEP'
ALTER TABLE [dbo].[CEP]
ADD CONSTRAINT [PK_CEP]
    PRIMARY KEY CLUSTERED ([ID_CEP] ASC);
GO

-- Creating primary key on [ID_CFOP] in table 'CFOP'
ALTER TABLE [dbo].[CFOP]
ADD CONSTRAINT [PK_CFOP]
    PRIMARY KEY CLUSTERED ([ID_CFOP] ASC);
GO

-- Creating primary key on [ID_CIRURGIA] in table 'CIRURGIA'
ALTER TABLE [dbo].[CIRURGIA]
ADD CONSTRAINT [PK_CIRURGIA]
    PRIMARY KEY CLUSTERED ([ID_CIRURGIA] ASC);
GO

-- Creating primary key on [COD_CLIENTE] in table 'CLIENTES'
ALTER TABLE [dbo].[CLIENTES]
ADD CONSTRAINT [PK_CLIENTES]
    PRIMARY KEY CLUSTERED ([COD_CLIENTE] ASC);
GO

-- Creating primary key on [Id] in table 'Compromissos'
ALTER TABLE [dbo].[Compromissos]
ADD CONSTRAINT [PK_Compromissos]
    PRIMARY KEY CLUSTERED ([Id] ASC);
GO

-- Creating primary key on [ID_CONFIG] in table 'CONFIG'
ALTER TABLE [dbo].[CONFIG]
ADD CONSTRAINT [PK_CONFIG]
    PRIMARY KEY CLUSTERED ([ID_CONFIG] ASC);
GO

-- Creating primary key on [ID_EMAIL] in table 'EMAIL'
ALTER TABLE [dbo].[EMAIL]
ADD CONSTRAINT [PK_EMAIL]
    PRIMARY KEY CLUSTERED ([ID_EMAIL] ASC);
GO

-- Creating primary key on [ID_EMPRESA] in table 'EMPRESA'
ALTER TABLE [dbo].[EMPRESA]
ADD CONSTRAINT [PK_EMPRESA]
    PRIMARY KEY CLUSTERED ([ID_EMPRESA] ASC);
GO

-- Creating primary key on [ID_ASSOCIACAO] in table 'EMPRESA_EMAIL'
ALTER TABLE [dbo].[EMPRESA_EMAIL]
ADD CONSTRAINT [PK_EMPRESA_EMAIL]
    PRIMARY KEY CLUSTERED ([ID_ASSOCIACAO] ASC);
GO

-- Creating primary key on [ID_ASSOCIACAO] in table 'EMPRESA_USUARIO'
ALTER TABLE [dbo].[EMPRESA_USUARIO]
ADD CONSTRAINT [PK_EMPRESA_USUARIO]
    PRIMARY KEY CLUSTERED ([ID_ASSOCIACAO] ASC);
GO

-- Creating primary key on [ID_ASSOCIACAO] in table 'EMPRESA_VETERINARIO'
ALTER TABLE [dbo].[EMPRESA_VETERINARIO]
ADD CONSTRAINT [PK_EMPRESA_VETERINARIO]
    PRIMARY KEY CLUSTERED ([ID_ASSOCIACAO] ASC);
GO

-- Creating primary key on [COD_GRP] in table 'GRP'
ALTER TABLE [dbo].[GRP]
ADD CONSTRAINT [PK_GRP]
    PRIMARY KEY CLUSTERED ([COD_GRP] ASC);
GO

-- Creating primary key on [ID_INTERNACAO] in table 'INTERNACAO'
ALTER TABLE [dbo].[INTERNACAO]
ADD CONSTRAINT [PK_INTERNACAO]
    PRIMARY KEY CLUSTERED ([ID_INTERNACAO] ASC);
GO

-- Creating primary key on [ID_PAGAMENTOS] in table 'PAGAMENTOS'
ALTER TABLE [dbo].[PAGAMENTOS]
ADD CONSTRAINT [PK_PAGAMENTOS]
    PRIMARY KEY CLUSTERED ([ID_PAGAMENTOS] ASC);
GO

-- Creating primary key on [ID_ASSOCIACAO] in table 'PAGAMENTOS_ATENDIMENTOS'
ALTER TABLE [dbo].[PAGAMENTOS_ATENDIMENTOS]
ADD CONSTRAINT [PK_PAGAMENTOS_ATENDIMENTOS]
    PRIMARY KEY CLUSTERED ([ID_ASSOCIACAO] ASC);
GO

-- Creating primary key on [ID_ASSOCIACAO] in table 'PAGAMENTOS_INTERNACAO'
ALTER TABLE [dbo].[PAGAMENTOS_INTERNACAO]
ADD CONSTRAINT [PK_PAGAMENTOS_INTERNACAO]
    PRIMARY KEY CLUSTERED ([ID_ASSOCIACAO] ASC);
GO

-- Creating primary key on [ID_PERFIL] in table 'PERFIL'
ALTER TABLE [dbo].[PERFIL]
ADD CONSTRAINT [PK_PERFIL]
    PRIMARY KEY CLUSTERED ([ID_PERFIL] ASC);
GO

-- Creating primary key on [ID_PET] in table 'PETS'
ALTER TABLE [dbo].[PETS]
ADD CONSTRAINT [PK_PETS]
    PRIMARY KEY CLUSTERED ([ID_PET] ASC);
GO

-- Creating primary key on [ID_PROPRIETARIO] in table 'PROPRIETARIOS'
ALTER TABLE [dbo].[PROPRIETARIOS]
ADD CONSTRAINT [PK_PROPRIETARIOS]
    PRIMARY KEY CLUSTERED ([ID_PROPRIETARIO] ASC);
GO

-- Creating primary key on [ID_RECEITA] in table 'RECEITA'
ALTER TABLE [dbo].[RECEITA]
ADD CONSTRAINT [PK_RECEITA]
    PRIMARY KEY CLUSTERED ([ID_RECEITA] ASC);
GO

-- Creating primary key on [ID_SERVICO] in table 'SERVICO'
ALTER TABLE [dbo].[SERVICO]
ADD CONSTRAINT [PK_SERVICO]
    PRIMARY KEY CLUSTERED ([ID_SERVICO] ASC);
GO

-- Creating primary key on [ID_ASSOCIACAO] in table 'SERVICO_VETERINARIO'
ALTER TABLE [dbo].[SERVICO_VETERINARIO]
ADD CONSTRAINT [PK_SERVICO_VETERINARIO]
    PRIMARY KEY CLUSTERED ([ID_ASSOCIACAO] ASC);
GO

-- Creating primary key on [ID_ASSOCIACAO] in table 'TOTAL_ATENDIMENTO'
ALTER TABLE [dbo].[TOTAL_ATENDIMENTO]
ADD CONSTRAINT [PK_TOTAL_ATENDIMENTO]
    PRIMARY KEY CLUSTERED ([ID_ASSOCIACAO] ASC);
GO

-- Creating primary key on [ID_ASSOCIACAO] in table 'TOTAL_INTERNACAO_CIRURGIA'
ALTER TABLE [dbo].[TOTAL_INTERNACAO_CIRURGIA]
ADD CONSTRAINT [PK_TOTAL_INTERNACAO_CIRURGIA]
    PRIMARY KEY CLUSTERED ([ID_ASSOCIACAO] ASC);
GO

-- Creating primary key on [ID_TRIB] in table 'Tributacao'
ALTER TABLE [dbo].[Tributacao]
ADD CONSTRAINT [PK_Tributacao]
    PRIMARY KEY CLUSTERED ([ID_TRIB] ASC);
GO

-- Creating primary key on [Id_USUARIO] in table 'USUARIOS'
ALTER TABLE [dbo].[USUARIOS]
ADD CONSTRAINT [PK_USUARIOS]
    PRIMARY KEY CLUSTERED ([Id_USUARIO] ASC);
GO

-- Creating primary key on [ID_ASSOCIACAO] in table 'VET_CIRURGIA'
ALTER TABLE [dbo].[VET_CIRURGIA]
ADD CONSTRAINT [PK_VET_CIRURGIA]
    PRIMARY KEY CLUSTERED ([ID_ASSOCIACAO] ASC);
GO

-- Creating primary key on [ID_VET] in table 'Veterinarios'
ALTER TABLE [dbo].[Veterinarios]
ADD CONSTRAINT [PK_Veterinarios]
    PRIMARY KEY CLUSTERED ([ID_VET] ASC);
GO

-- Creating primary key on [ID_TAXAS] in table 'TAXAS'
ALTER TABLE [dbo].[TAXAS]
ADD CONSTRAINT [PK_TAXAS]
    PRIMARY KEY CLUSTERED ([ID_TAXAS] ASC);
GO

-- Creating primary key on [NOME_PET], [ID_PET], [RACA_PET], [SEXO_PET], [NOME_PROPRIETARIO], [ATIVO], [RAZAO_SOCIAL] in table 'b_pessoas_empresa_pet'
ALTER TABLE [dbo].[b_pessoas_empresa_pet]
ADD CONSTRAINT [PK_b_pessoas_empresa_pet]
    PRIMARY KEY CLUSTERED ([NOME_PET], [ID_PET], [RACA_PET], [SEXO_PET], [NOME_PROPRIETARIO], [ATIVO], [RAZAO_SOCIAL] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [ID_ATENDIMENTO] in table 'INTERNACAO'
ALTER TABLE [dbo].[INTERNACAO]
ADD CONSTRAINT [FK_ATENDIMENTO_VETINTERNACAO]
    FOREIGN KEY ([ID_ATENDIMENTO])
    REFERENCES [dbo].[ATENDIMENTO_VET]
        ([ID_ATENDIMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ATENDIMENTO_VETINTERNACAO'
CREATE INDEX [IX_FK_ATENDIMENTO_VETINTERNACAO]
ON [dbo].[INTERNACAO]
    ([ID_ATENDIMENTO]);
GO

-- Creating foreign key on [ID_ATENDIMENTO] in table 'RECEITA'
ALTER TABLE [dbo].[RECEITA]
ADD CONSTRAINT [FK_ATENDIMENTO_VETRECEITA]
    FOREIGN KEY ([ID_ATENDIMENTO])
    REFERENCES [dbo].[ATENDIMENTO_VET]
        ([ID_ATENDIMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ATENDIMENTO_VETRECEITA'
CREATE INDEX [IX_FK_ATENDIMENTO_VETRECEITA]
ON [dbo].[RECEITA]
    ([ID_ATENDIMENTO]);
GO

-- Creating foreign key on [ID_ATENDIMENTO] in table 'SERVICO_VETERINARIO'
ALTER TABLE [dbo].[SERVICO_VETERINARIO]
ADD CONSTRAINT [FK_ATENDIMENTO_VETSERVICO_VETERINARIO]
    FOREIGN KEY ([ID_ATENDIMENTO])
    REFERENCES [dbo].[ATENDIMENTO_VET]
        ([ID_ATENDIMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ATENDIMENTO_VETSERVICO_VETERINARIO'
CREATE INDEX [IX_FK_ATENDIMENTO_VETSERVICO_VETERINARIO]
ON [dbo].[SERVICO_VETERINARIO]
    ([ID_ATENDIMENTO]);
GO

-- Creating foreign key on [ID_ATENDIMENTO] in table 'TOTAL_ATENDIMENTO'
ALTER TABLE [dbo].[TOTAL_ATENDIMENTO]
ADD CONSTRAINT [FK_ATENDIMENTO_VETTOTAL_ATENDIMENTO]
    FOREIGN KEY ([ID_ATENDIMENTO])
    REFERENCES [dbo].[ATENDIMENTO_VET]
        ([ID_ATENDIMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ATENDIMENTO_VETTOTAL_ATENDIMENTO'
CREATE INDEX [IX_FK_ATENDIMENTO_VETTOTAL_ATENDIMENTO]
ON [dbo].[TOTAL_ATENDIMENTO]
    ([ID_ATENDIMENTO]);
GO

-- Creating foreign key on [ID_CIRURGIA] in table 'ATENDIMENTO_VET'
ALTER TABLE [dbo].[ATENDIMENTO_VET]
ADD CONSTRAINT [FK_CIRURGIAATENDIMENTO_VET]
    FOREIGN KEY ([ID_CIRURGIA])
    REFERENCES [dbo].[CIRURGIA]
        ([ID_CIRURGIA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CIRURGIAATENDIMENTO_VET'
CREATE INDEX [IX_FK_CIRURGIAATENDIMENTO_VET]
ON [dbo].[ATENDIMENTO_VET]
    ([ID_CIRURGIA]);
GO

-- Creating foreign key on [ID_CLIENTE] in table 'ATENDIMENTO_VET'
ALTER TABLE [dbo].[ATENDIMENTO_VET]
ADD CONSTRAINT [FK_ClienteATENDIMENTO_VET]
    FOREIGN KEY ([ID_CLIENTE])
    REFERENCES [dbo].[PROPRIETARIOS]
        ([ID_PROPRIETARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ClienteATENDIMENTO_VET'
CREATE INDEX [IX_FK_ClienteATENDIMENTO_VET]
ON [dbo].[ATENDIMENTO_VET]
    ([ID_CLIENTE]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'ATENDIMENTO_VET'
ALTER TABLE [dbo].[ATENDIMENTO_VET]
ADD CONSTRAINT [FK_EMPRESAATENDIMENTO_VET]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESAATENDIMENTO_VET'
CREATE INDEX [IX_FK_EMPRESAATENDIMENTO_VET]
ON [dbo].[ATENDIMENTO_VET]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_PET] in table 'ATENDIMENTO_VET'
ALTER TABLE [dbo].[ATENDIMENTO_VET]
ADD CONSTRAINT [FK_PETATENDIMENTO_VET]
    FOREIGN KEY ([ID_PET])
    REFERENCES [dbo].[PETS]
        ([ID_PET])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PETATENDIMENTO_VET'
CREATE INDEX [IX_FK_PETATENDIMENTO_VET]
ON [dbo].[ATENDIMENTO_VET]
    ([ID_PET]);
GO

-- Creating foreign key on [ID_VET] in table 'ATENDIMENTO_VET'
ALTER TABLE [dbo].[ATENDIMENTO_VET]
ADD CONSTRAINT [FK_VeterinariosATENDIMENTO_VET]
    FOREIGN KEY ([ID_VET])
    REFERENCES [dbo].[Veterinarios]
        ([ID_VET])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_VeterinariosATENDIMENTO_VET'
CREATE INDEX [IX_FK_VeterinariosATENDIMENTO_VET]
ON [dbo].[ATENDIMENTO_VET]
    ([ID_VET]);
GO

-- Creating foreign key on [ID_CIRURGIA] in table 'INTERNACAO'
ALTER TABLE [dbo].[INTERNACAO]
ADD CONSTRAINT [FK_CIRURGIAINTERNACAO]
    FOREIGN KEY ([ID_CIRURGIA])
    REFERENCES [dbo].[CIRURGIA]
        ([ID_CIRURGIA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CIRURGIAINTERNACAO'
CREATE INDEX [IX_FK_CIRURGIAINTERNACAO]
ON [dbo].[INTERNACAO]
    ([ID_CIRURGIA]);
GO

-- Creating foreign key on [ID_CIRURGIA] in table 'TOTAL_INTERNACAO_CIRURGIA'
ALTER TABLE [dbo].[TOTAL_INTERNACAO_CIRURGIA]
ADD CONSTRAINT [FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA]
    FOREIGN KEY ([ID_CIRURGIA])
    REFERENCES [dbo].[CIRURGIA]
        ([ID_CIRURGIA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA'
CREATE INDEX [IX_FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA]
ON [dbo].[TOTAL_INTERNACAO_CIRURGIA]
    ([ID_CIRURGIA]);
GO

-- Creating foreign key on [ID_CIRURGIA] in table 'TOTAL_INTERNACAO_CIRURGIA'
ALTER TABLE [dbo].[TOTAL_INTERNACAO_CIRURGIA]
ADD CONSTRAINT [FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA1]
    FOREIGN KEY ([ID_CIRURGIA])
    REFERENCES [dbo].[CIRURGIA]
        ([ID_CIRURGIA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA1'
CREATE INDEX [IX_FK_CIRURGIATOTAL_INTERNACAO_CIRURGIA1]
ON [dbo].[TOTAL_INTERNACAO_CIRURGIA]
    ([ID_CIRURGIA]);
GO

-- Creating foreign key on [ID_CIRURGIA] in table 'VET_CIRURGIA'
ALTER TABLE [dbo].[VET_CIRURGIA]
ADD CONSTRAINT [FK_CIRURGIAVET_CIRURGIA]
    FOREIGN KEY ([ID_CIRURGIA])
    REFERENCES [dbo].[CIRURGIA]
        ([ID_CIRURGIA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CIRURGIAVET_CIRURGIA'
CREATE INDEX [IX_FK_CIRURGIAVET_CIRURGIA]
ON [dbo].[VET_CIRURGIA]
    ([ID_CIRURGIA]);
GO

-- Creating foreign key on [ID_CLIENTE] in table 'CIRURGIA'
ALTER TABLE [dbo].[CIRURGIA]
ADD CONSTRAINT [FK_ClienteCIRURGIA]
    FOREIGN KEY ([ID_CLIENTE])
    REFERENCES [dbo].[PROPRIETARIOS]
        ([ID_PROPRIETARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ClienteCIRURGIA'
CREATE INDEX [IX_FK_ClienteCIRURGIA]
ON [dbo].[CIRURGIA]
    ([ID_CLIENTE]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'CIRURGIA'
ALTER TABLE [dbo].[CIRURGIA]
ADD CONSTRAINT [FK_EMPRESACIRURGIA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESACIRURGIA'
CREATE INDEX [IX_FK_EMPRESACIRURGIA]
ON [dbo].[CIRURGIA]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_PET] in table 'CIRURGIA'
ALTER TABLE [dbo].[CIRURGIA]
ADD CONSTRAINT [FK_PETCIRURGIA]
    FOREIGN KEY ([ID_PET])
    REFERENCES [dbo].[PETS]
        ([ID_PET])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PETCIRURGIA'
CREATE INDEX [IX_FK_PETCIRURGIA]
ON [dbo].[CIRURGIA]
    ([ID_PET]);
GO

-- Creating foreign key on [ID_CIRURGIA] in table 'RECEITA'
ALTER TABLE [dbo].[RECEITA]
ADD CONSTRAINT [FK_RECEITACIRURGIA]
    FOREIGN KEY ([ID_CIRURGIA])
    REFERENCES [dbo].[CIRURGIA]
        ([ID_CIRURGIA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RECEITACIRURGIA'
CREATE INDEX [IX_FK_RECEITACIRURGIA]
ON [dbo].[RECEITA]
    ([ID_CIRURGIA]);
GO

-- Creating foreign key on [ID_VET_PRINCIPAL] in table 'CIRURGIA'
ALTER TABLE [dbo].[CIRURGIA]
ADD CONSTRAINT [FK_VeterinariosCIRURGIA]
    FOREIGN KEY ([ID_VET_PRINCIPAL])
    REFERENCES [dbo].[Veterinarios]
        ([ID_VET])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_VeterinariosCIRURGIA'
CREATE INDEX [IX_FK_VeterinariosCIRURGIA]
ON [dbo].[CIRURGIA]
    ([ID_VET_PRINCIPAL]);
GO

-- Creating foreign key on [ID_CONFIG] in table 'EMPRESA'
ALTER TABLE [dbo].[EMPRESA]
ADD CONSTRAINT [FK_EMPRESACONFIG]
    FOREIGN KEY ([ID_CONFIG])
    REFERENCES [dbo].[CONFIG]
        ([ID_CONFIG])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESACONFIG'
CREATE INDEX [IX_FK_EMPRESACONFIG]
ON [dbo].[EMPRESA]
    ([ID_CONFIG]);
GO

-- Creating foreign key on [ID_EMAIL] in table 'EMPRESA_EMAIL'
ALTER TABLE [dbo].[EMPRESA_EMAIL]
ADD CONSTRAINT [FK_EMAILEMPRESA_EMAIL]
    FOREIGN KEY ([ID_EMAIL])
    REFERENCES [dbo].[EMAIL]
        ([ID_EMAIL])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMAILEMPRESA_EMAIL'
CREATE INDEX [IX_FK_EMAILEMPRESA_EMAIL]
ON [dbo].[EMPRESA_EMAIL]
    ([ID_EMAIL]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'EMPRESA_EMAIL'
ALTER TABLE [dbo].[EMPRESA_EMAIL]
ADD CONSTRAINT [FK_EMPRESA_EMAIL1]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESA_EMAIL1'
CREATE INDEX [IX_FK_EMPRESA_EMAIL1]
ON [dbo].[EMPRESA_EMAIL]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'EMPRESA_USUARIO'
ALTER TABLE [dbo].[EMPRESA_USUARIO]
ADD CONSTRAINT [FK_EMPRESAEMPRESA_USUARIO]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESAEMPRESA_USUARIO'
CREATE INDEX [IX_FK_EMPRESAEMPRESA_USUARIO]
ON [dbo].[EMPRESA_USUARIO]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'EMPRESA_VETERINARIO'
ALTER TABLE [dbo].[EMPRESA_VETERINARIO]
ADD CONSTRAINT [FK_EMPRESAEMPRESA_VETERINARIO]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESAEMPRESA_VETERINARIO'
CREATE INDEX [IX_FK_EMPRESAEMPRESA_VETERINARIO]
ON [dbo].[EMPRESA_VETERINARIO]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'INTERNACAO'
ALTER TABLE [dbo].[INTERNACAO]
ADD CONSTRAINT [FK_EMPRESAINTERNACAO]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESAINTERNACAO'
CREATE INDEX [IX_FK_EMPRESAINTERNACAO]
ON [dbo].[INTERNACAO]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_USUARIO] in table 'EMPRESA_USUARIO'
ALTER TABLE [dbo].[EMPRESA_USUARIO]
ADD CONSTRAINT [FK_USUARIOSEMPRESA_USUARIO]
    FOREIGN KEY ([ID_USUARIO])
    REFERENCES [dbo].[USUARIOS]
        ([Id_USUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USUARIOSEMPRESA_USUARIO'
CREATE INDEX [IX_FK_USUARIOSEMPRESA_USUARIO]
ON [dbo].[EMPRESA_USUARIO]
    ([ID_USUARIO]);
GO

-- Creating foreign key on [ID_VET] in table 'EMPRESA_VETERINARIO'
ALTER TABLE [dbo].[EMPRESA_VETERINARIO]
ADD CONSTRAINT [FK_VeterinariosEMPRESA_VETERINARIO]
    FOREIGN KEY ([ID_VET])
    REFERENCES [dbo].[Veterinarios]
        ([ID_VET])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_VeterinariosEMPRESA_VETERINARIO'
CREATE INDEX [IX_FK_VeterinariosEMPRESA_VETERINARIO]
ON [dbo].[EMPRESA_VETERINARIO]
    ([ID_VET]);
GO

-- Creating foreign key on [ID_CLIENTE] in table 'INTERNACAO'
ALTER TABLE [dbo].[INTERNACAO]
ADD CONSTRAINT [FK_ClienteINTERNACAO]
    FOREIGN KEY ([ID_CLIENTE])
    REFERENCES [dbo].[PROPRIETARIOS]
        ([ID_PROPRIETARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ClienteINTERNACAO'
CREATE INDEX [IX_FK_ClienteINTERNACAO]
ON [dbo].[INTERNACAO]
    ([ID_CLIENTE]);
GO

-- Creating foreign key on [ID_INTERNACAO] in table 'RECEITA'
ALTER TABLE [dbo].[RECEITA]
ADD CONSTRAINT [FK_INTERNACAORECEITA]
    FOREIGN KEY ([ID_INTERNACAO])
    REFERENCES [dbo].[INTERNACAO]
        ([ID_INTERNACAO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_INTERNACAORECEITA'
CREATE INDEX [IX_FK_INTERNACAORECEITA]
ON [dbo].[RECEITA]
    ([ID_INTERNACAO]);
GO

-- Creating foreign key on [ID_INTERNACAO] in table 'SERVICO_VETERINARIO'
ALTER TABLE [dbo].[SERVICO_VETERINARIO]
ADD CONSTRAINT [FK_INTERNACAOSERVICO_VETERINARIO]
    FOREIGN KEY ([ID_INTERNACAO])
    REFERENCES [dbo].[INTERNACAO]
        ([ID_INTERNACAO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_INTERNACAOSERVICO_VETERINARIO'
CREATE INDEX [IX_FK_INTERNACAOSERVICO_VETERINARIO]
ON [dbo].[SERVICO_VETERINARIO]
    ([ID_INTERNACAO]);
GO

-- Creating foreign key on [ID_INTERNACAO] in table 'TOTAL_INTERNACAO_CIRURGIA'
ALTER TABLE [dbo].[TOTAL_INTERNACAO_CIRURGIA]
ADD CONSTRAINT [FK_INTERNACAOTOTAL_INTERNACAO]
    FOREIGN KEY ([ID_INTERNACAO])
    REFERENCES [dbo].[INTERNACAO]
        ([ID_INTERNACAO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_INTERNACAOTOTAL_INTERNACAO'
CREATE INDEX [IX_FK_INTERNACAOTOTAL_INTERNACAO]
ON [dbo].[TOTAL_INTERNACAO_CIRURGIA]
    ([ID_INTERNACAO]);
GO

-- Creating foreign key on [ID_PET] in table 'INTERNACAO'
ALTER TABLE [dbo].[INTERNACAO]
ADD CONSTRAINT [FK_PETINTERNACAO]
    FOREIGN KEY ([ID_PET])
    REFERENCES [dbo].[PETS]
        ([ID_PET])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PETINTERNACAO'
CREATE INDEX [IX_FK_PETINTERNACAO]
ON [dbo].[INTERNACAO]
    ([ID_PET]);
GO

-- Creating foreign key on [ID_VET] in table 'INTERNACAO'
ALTER TABLE [dbo].[INTERNACAO]
ADD CONSTRAINT [FK_VeterinariosINTERNACAO]
    FOREIGN KEY ([ID_VET])
    REFERENCES [dbo].[Veterinarios]
        ([ID_VET])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_VeterinariosINTERNACAO'
CREATE INDEX [IX_FK_VeterinariosINTERNACAO]
ON [dbo].[INTERNACAO]
    ([ID_VET]);
GO

-- Creating foreign key on [ID_PAGAMENTO] in table 'PAGAMENTOS_ATENDIMENTOS'
ALTER TABLE [dbo].[PAGAMENTOS_ATENDIMENTOS]
ADD CONSTRAINT [FK_PAGAMENTOSPAGAMENTOS_ATENDIMENTO]
    FOREIGN KEY ([ID_PAGAMENTO])
    REFERENCES [dbo].[PAGAMENTOS]
        ([ID_PAGAMENTOS])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PAGAMENTOSPAGAMENTOS_ATENDIMENTO'
CREATE INDEX [IX_FK_PAGAMENTOSPAGAMENTOS_ATENDIMENTO]
ON [dbo].[PAGAMENTOS_ATENDIMENTOS]
    ([ID_PAGAMENTO]);
GO

-- Creating foreign key on [ID_PAGAMENTO] in table 'PAGAMENTOS_INTERNACAO'
ALTER TABLE [dbo].[PAGAMENTOS_INTERNACAO]
ADD CONSTRAINT [FK_PAGAMENTOSPAGAMENTOS_INTERNACAO]
    FOREIGN KEY ([ID_PAGAMENTO])
    REFERENCES [dbo].[PAGAMENTOS]
        ([ID_PAGAMENTOS])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PAGAMENTOSPAGAMENTOS_INTERNACAO'
CREATE INDEX [IX_FK_PAGAMENTOSPAGAMENTOS_INTERNACAO]
ON [dbo].[PAGAMENTOS_INTERNACAO]
    ([ID_PAGAMENTO]);
GO

-- Creating foreign key on [ID_TIPO_ATENDIMENTO] in table 'PAGAMENTOS_ATENDIMENTOS'
ALTER TABLE [dbo].[PAGAMENTOS_ATENDIMENTOS]
ADD CONSTRAINT [FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO]
    FOREIGN KEY ([ID_TIPO_ATENDIMENTO])
    REFERENCES [dbo].[TOTAL_ATENDIMENTO]
        ([ID_ASSOCIACAO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO'
CREATE INDEX [IX_FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO]
ON [dbo].[PAGAMENTOS_ATENDIMENTOS]
    ([ID_TIPO_ATENDIMENTO]);
GO

-- Creating foreign key on [ID_TIPO_ATENDIMENTO] in table 'PAGAMENTOS_INTERNACAO'
ALTER TABLE [dbo].[PAGAMENTOS_INTERNACAO]
ADD CONSTRAINT [FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO1]
    FOREIGN KEY ([ID_TIPO_ATENDIMENTO])
    REFERENCES [dbo].[TOTAL_INTERNACAO_CIRURGIA]
        ([ID_ASSOCIACAO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO1'
CREATE INDEX [IX_FK_TOTAL_ATENDIMENTOPAGAMENTOS_ATENDIMENTO1]
ON [dbo].[PAGAMENTOS_INTERNACAO]
    ([ID_TIPO_ATENDIMENTO]);
GO

-- Creating foreign key on [ID_PERFIL] in table 'USUARIOS'
ALTER TABLE [dbo].[USUARIOS]
ADD CONSTRAINT [FK_PERFILUSUARIOS]
    FOREIGN KEY ([ID_PERFIL])
    REFERENCES [dbo].[PERFIL]
        ([ID_PERFIL])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERFILUSUARIOS'
CREATE INDEX [IX_FK_PERFILUSUARIOS]
ON [dbo].[USUARIOS]
    ([ID_PERFIL]);
GO

-- Creating foreign key on [COD_CLIENTE] in table 'PETS'
ALTER TABLE [dbo].[PETS]
ADD CONSTRAINT [FK_PETCliente]
    FOREIGN KEY ([COD_CLIENTE])
    REFERENCES [dbo].[PROPRIETARIOS]
        ([ID_PROPRIETARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PETCliente'
CREATE INDEX [IX_FK_PETCliente]
ON [dbo].[PETS]
    ([COD_CLIENTE]);
GO

-- Creating foreign key on [ID_SERVICO] in table 'SERVICO_VETERINARIO'
ALTER TABLE [dbo].[SERVICO_VETERINARIO]
ADD CONSTRAINT [FK_SERVICOSERVICO_VETERINARIO]
    FOREIGN KEY ([ID_SERVICO])
    REFERENCES [dbo].[SERVICO]
        ([ID_SERVICO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SERVICOSERVICO_VETERINARIO'
CREATE INDEX [IX_FK_SERVICOSERVICO_VETERINARIO]
ON [dbo].[SERVICO_VETERINARIO]
    ([ID_SERVICO]);
GO

-- Creating foreign key on [ID_VET] in table 'SERVICO_VETERINARIO'
ALTER TABLE [dbo].[SERVICO_VETERINARIO]
ADD CONSTRAINT [FK_VeterinariosSERVICO_VETERINARIO]
    FOREIGN KEY ([ID_VET])
    REFERENCES [dbo].[Veterinarios]
        ([ID_VET])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_VeterinariosSERVICO_VETERINARIO'
CREATE INDEX [IX_FK_VeterinariosSERVICO_VETERINARIO]
ON [dbo].[SERVICO_VETERINARIO]
    ([ID_VET]);
GO

-- Creating foreign key on [ID_VET] in table 'VET_CIRURGIA'
ALTER TABLE [dbo].[VET_CIRURGIA]
ADD CONSTRAINT [FK_VeterinariosVET_CIRURGIA]
    FOREIGN KEY ([ID_VET])
    REFERENCES [dbo].[Veterinarios]
        ([ID_VET])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_VeterinariosVET_CIRURGIA'
CREATE INDEX [IX_FK_VeterinariosVET_CIRURGIA]
ON [dbo].[VET_CIRURGIA]
    ([ID_VET]);
GO

-- Creating foreign key on [ID_TAXAS] in table 'PAGAMENTOS'
ALTER TABLE [dbo].[PAGAMENTOS]
ADD CONSTRAINT [FK_TAXASPAGAMENTOS]
    FOREIGN KEY ([ID_TAXAS])
    REFERENCES [dbo].[TAXAS]
        ([ID_TAXAS])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TAXASPAGAMENTOS'
CREATE INDEX [IX_FK_TAXASPAGAMENTOS]
ON [dbo].[PAGAMENTOS]
    ([ID_TAXAS]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------