//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPetshop_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGAMENTOS_ATENDIMENTOS
    {
        public int ID_ASSOCIACAO { get; set; }
        public int ID_PAGAMENTO { get; set; }
        public string NOME_PAGAMENTO { get; set; }
        public decimal VALOR_PAGAMENTO { get; set; }
        public int ID_TIPO_ATENDIMENTO { get; set; }
        public Nullable<int> DIVIDO_VEZES { get; set; }
        public System.DateTime DATA_FECHAMENTO { get; set; }
    
        public virtual PAGAMENTOS PAGAMENTOS { get; set; }
        public virtual TOTAL_ATENDIMENTO TOTAL_ATENDIMENTO { get; set; }
    }
}
