//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPetshop_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICO_VETERINARIO
    {
        public int ID_ASSOCIACAO { get; set; }
        public int ID_SERVICO { get; set; }
        public string NOME_SERVICO { get; set; }
        public decimal VALOR_SERVICO { get; set; }
        public Nullable<int> ID_ATENDIMENTO { get; set; }
        public Nullable<int> ID_INTERNACAO { get; set; }
        public int ID_VET { get; set; }
        public System.DateTime DATA_EXECUCAO { get; set; }
    
        public virtual ATENDIMENTO_VET ATENDIMENTO_VET { get; set; }
        public virtual INTERNACAO INTERNACAO { get; set; }
        public virtual SERVICO SERVICO { get; set; }
        public virtual Veterinarios Veterinarios { get; set; }
    }
}
