//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPetshop_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tributacao
    {
        public int ID_TRIB { get; set; }
        public string TRBID { get; set; }
        public string NOME { get; set; }
        public string CST_ENTRADA { get; set; }
        public string CSOSN_ENTRADA { get; set; }
        public string CFOP_ENTRADA_DE { get; set; }
        public string CFOP_ENTRADA_DEV_DE { get; set; }
        public string CFOP_ENTRADA_DEV_FE { get; set; }
        public string CFOP_ENTRADA_FE { get; set; }
        public string CST_SAIDA { get; set; }
        public string CSOSN_SAIDA { get; set; }
        public string CFOP_SAIDA_DE { get; set; }
        public string CFOP_SAIDA_FE { get; set; }
        public string CFOP_SAIDA_DEV_DE { get; set; }
        public string CFOP_SAIDA_DEV_FE { get; set; }
        public string ATIVO { get; set; }
    }
}
